apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-session-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-session-scaler
  template:
    metadata:
      labels:
        app: redis-session-scaler
    spec:
      containers:
        - name: scaler
          image: docker.io/ebinsu/redis-session-scaler:1.0
          env:
            - name: REDIS_ADDRESS
              value: "redis-nodeport:6379"
          ports:
            - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: redis-session-scaler
spec:
  ports:
    - port: 6000
      targetPort: 6000
  selector:
    app: redis-session-scaler
